/**Jenkinsfile for creating triggers for PollSCM, WebHook, Cron
**/


pipeline{
    agent any
    triggers{
        pollCM('H/15 * * *')//pollSCM trigger
        cron('0 2 * * *')//Cron trigger
    }
    stages{
        stage('stage1'){
            steps{
                echo "stage1 complete" //workflow commands
            }
        }
    }
}