pipeline{
    agent any
    triggers{
        pollSCM('H/15 * * *')
    }
    stages{
        stage('stage1'){
            steps{
                echo "stage1 complete" //workflow commands
            }
        }
    }
}